version: "3"

services:
  db:
    container_name: db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./back/tmp/db:/var/lib/postgresql/data
    networks:
      - app_network

  back:
    container_name: back
    build: back/
    volumes:
      - ./back:/app
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - app_network

  front:
    container_name: front
    build: front/
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    depends_on:
      - back
    networks:
      - app_network

networks:
  app_network: